<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="ControlTemp" Id="{d3f6de43-3b57-4ce0-885a-f730bb311d29}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM ControlTemp
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Calculo de la temperatura de los termicos
GVL.TempTerT:=IO.I_TermT*0.0244-0.0007;
GVL.TempTerb:=IO.I_TermB*0.0244-0.0007;]]></ST>
    </Implementation>
    <LineIds Name="ControlTemp">
      <LineId Id="6" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>