<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{d8de5791-f153-470a-bfaa-453c619a7f06}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	En:BOOL;
	Shot:BOOL;
	Result:ARRAY [0..7] OF REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Motion.InitMotion();
GVL.Vision();

//MedidaTempPuente();
MedidaTempTarjeta();
MedidaDiamMec();

OperatingModes();

IF GVL.Mode = Modes.AUTO THEN
	Basic();
END_IF

Manual();
VisuLogic();
Motion();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="49" Count="3" />
      <LineId Id="69" Count="0" />
      <LineId Id="53" Count="9" />
      <LineId Id="42" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>